### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ZhangYuan1998** [HKUDS/OpenCity#2]
作者您好！您的研究工作非常出色！我有一些关于数据集预训练的问题，想请教您。

针对不同类型的数据集，预训练应该如何进行？
假设我们简化问题，假设用于预训练的数据集包括[NYC-TAXI, TrafficZZ, METR-LA]。在这种情况下，训练中的一个epoch，是指完整地随机选择一个数据集进行训练吗？比如随机选择了NYC-TAXI，那么这个epoch会用NYC-TAXI的整个数据集进行训练。然后再随机选择其他的数据集进行训练，一直到模型在所有数据集上表现达到收敛？

其次，模型的参数是否与每个数据集的空间节点数量无关？
因为似乎只有在这种情况下，才能使用一个模型同时训练多个不同类型的数据集。

最后，模型运行有问题报错，在预训练的测试阶段运行python Run.py -mode pretrain -model OpenCity -save_pretrain_path OpenCity-mini2.0.pth -batch_size 16 --embed_dim 128 --skip_dim 128 --enc_depth 3时出现了如下错误：
![image](https://github.com/user-attachments/assets/98cea86b-7fe9-4f36-9aef-9a8a60b2b16e)

**Comment by LZH-YS1998** [comment]
您好，非常感谢您的关注。
1. 在预训练阶段，训练一个epoch会使用所有预训练数据集（例如[NYC-TAXI, TrafficZZ, METR-LA]）进行一轮训练。你可以通过更改val_ratio和test_ratio，以及在data_process.py中选定数据集范围。 所选数据都被随机打乱进行训练。我们选择10个epochs作为预训练轮次。
2. 模型参数与每个数据集节点数无关。
3. 这部分代码已经更改，val_ratio为0时不进行val，感谢。
